### PR TITLE
Update to v0.8 Alpha

### PR DESCRIPTION
**Pull request by RorschX1**

### CODE REVIEW

**Comment by Varynn** [comment]
Can't find a forum thread so I'm asking here. This is to make the HTC Usonic ear buds work right?

**Comment by RorschX1** [comment]
First, HTC Usonic earbuds needs USB-Type C
Second, this apk doesn't have UI (Maybe need work with HTC Sense).
But the service and libs are working...

Test on my HTC ONE M7 running AOSP 7.1.1

**Comment by cheng-x** [comment]
```
04-12 18:15:49.583  1060  1060 W InstallerConnection: installd not ready
04-12 18:15:50.118   678   706 I ServiceManager: Waiting for service sensorservice...
04-12 18:15:50.584  1060  1060 I InstallerConnection: connecting...
04-12 18:15:50.587  1060  1060 I InstallerConnection: disconnecting...
04-12 18:15:50.588  1060  1060 E InstallerConnection: connection failed
04-12 18:15:50.589  1060  1060 W InstallerConnection: installd not ready
04-12 18:15:51.119   678   706 I ServiceManager: Waiting for service sensorservice...
```

On Xiaomi mi5 AOSP 7.1.2

**Comment by Love4Taylor** [comment]
You are the contributor of this repository, why use PR instead of submitting code directly

**Comment by RorschX1** [comment]
image

**Comment by Love4Taylor** [comment]
@RorschX1 Maybe you should check your mail
image

**Comment by RorschX1** [comment]
Thanks!

**Comment by RorschX1** [comment]
👍

**Pull request merged**
